### ISSUE TITLE
rust-lldb

### ISSUE THREAD

**Issue by Yamakaky** [critiqjo/lldb.nvim#19]
For rust, do you use rust-lldb instead of lldb if it's installed ? 
https://michaelwoerister.github.io/2015/03/27/rust-xxdb.html

**Comment by critiqjo** [comment]
`rust-lldb` is just a python script, which is used only to pretty print variables. You can simply execute these LLDB commands to use it:
```
command script import "path/to/lldb_rust_formatters.py"
type summary add --no-value --python-function lldb_rust_formatters.print_val -x \".*\" --category Rust
type category enable Rust
```
The directory containing `lldb_rust_formatters.py` should also contain `debugger_pretty_printers_common.py`. That's it!

I don't use it often though, because indentation gets messed up when printing a variable using it.
Just do `type category disable Rust` to disable it.

source: https://github.com/rust-lang/rust/blob/master/src/etc/rust-lldb

**Comment by critiqjo** [comment]
I believe the confusion is resolved... Closing...
